/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceParkingSlotData
 */
public class ServiceParkingSlotDataTest {
    private final ServiceParkingSlotData model = new ServiceParkingSlotData();

    /**
     * Model tests for ServiceParkingSlotData
     */
    @Test
    public void testServiceParkingSlotData() {
        // TODO: test ServiceParkingSlotData
    }

    /**
     * Test the property 'attended'
     */
    @Test
    public void attendedTest() {
        // TODO: test attended
    }

    /**
     * Test the property 'callId'
     */
    @Test
    public void callIdTest() {
        // TODO: test callId
    }

    /**
     * Test the property 'cidName'
     */
    @Test
    public void cidNameTest() {
        // TODO: test cidName
    }

    /**
     * Test the property 'cidNumber'
     */
    @Test
    public void cidNumberTest() {
        // TODO: test cidNumber
    }

    /**
     * Test the property 'cidUri'
     */
    @Test
    public void cidUriTest() {
        // TODO: test cidUri
    }

    /**
     * Test the property 'fromTag'
     */
    @Test
    public void fromTagTest() {
        // TODO: test fromTag
    }

    /**
     * Test the property 'node'
     */
    @Test
    public void nodeTest() {
        // TODO: test node
    }

    /**
     * Test the property 'presenceId'
     */
    @Test
    public void presenceIdTest() {
        // TODO: test presenceId
    }

    /**
     * Test the property 'presenceRealm'
     */
    @Test
    public void presenceRealmTest() {
        // TODO: test presenceRealm
    }

    /**
     * Test the property 'presenceType'
     */
    @Test
    public void presenceTypeTest() {
        // TODO: test presenceType
    }

    /**
     * Test the property 'presenceUser'
     */
    @Test
    public void presenceUserTest() {
        // TODO: test presenceUser
    }

    /**
     * Test the property 'ringbackId'
     */
    @Test
    public void ringbackIdTest() {
        // TODO: test ringbackId
    }

    /**
     * Test the property 'slotCallId'
     */
    @Test
    public void slotCallIdTest() {
        // TODO: test slotCallId
    }

    /**
     * Test the property 'switchUri'
     */
    @Test
    public void switchUriTest() {
        // TODO: test switchUri
    }

    /**
     * Test the property 'toTag'
     */
    @Test
    public void toTagTest() {
        // TODO: test toTag
    }

}
