/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceVOIPVoicemailMessageAddData
 */
public class ServiceVOIPVoicemailMessageAddDataTest {
    private final ServiceVOIPVoicemailMessageAddData model = new ServiceVOIPVoicemailMessageAddData();

    /**
     * Model tests for ServiceVOIPVoicemailMessageAddData
     */
    @Test
    public void testServiceVOIPVoicemailMessageAddData() {
        // TODO: test ServiceVOIPVoicemailMessageAddData
    }

    /**
     * Test the property 'callerIdName'
     */
    @Test
    public void callerIdNameTest() {
        // TODO: test callerIdName
    }

    /**
     * Test the property 'callerIdNumber'
     */
    @Test
    public void callerIdNumberTest() {
        // TODO: test callerIdNumber
    }

    /**
     * Test the property 'folder'
     */
    @Test
    public void folderTest() {
        // TODO: test folder
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

}
