/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceVoicemailMessageOutput
 */
public class ServiceVoicemailMessageOutputTest {
    private final ServiceVoicemailMessageOutput model = new ServiceVoicemailMessageOutput();

    /**
     * Model tests for ServiceVoicemailMessageOutput
     */
    @Test
    public void testServiceVoicemailMessageOutput() {
        // TODO: test ServiceVoicemailMessageOutput
    }

    /**
     * Test the property 'callId'
     */
    @Test
    public void callIdTest() {
        // TODO: test callId
    }

    /**
     * Test the property 'callerIdName'
     */
    @Test
    public void callerIdNameTest() {
        // TODO: test callerIdName
    }

    /**
     * Test the property 'callerIdNumber'
     */
    @Test
    public void callerIdNumberTest() {
        // TODO: test callerIdNumber
    }

    /**
     * Test the property 'folder'
     */
    @Test
    public void folderTest() {
        // TODO: test folder
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'length'
     */
    @Test
    public void lengthTest() {
        // TODO: test length
    }

    /**
     * Test the property 'mediaId'
     */
    @Test
    public void mediaIdTest() {
        // TODO: test mediaId
    }

    /**
     * Test the property 'succeeded'
     */
    @Test
    public void succeededTest() {
        // TODO: test succeeded
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

}
