/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ModelsCallForward;
import org.openapitools.client.model.ModelsCallRecordingSettings;
import org.openapitools.client.model.ModelsMusicOnHold;
import org.openapitools.client.model.ModelsUserOutputFullCallerid;
import org.openapitools.client.model.ModelsVOIPSharedDoNotDisturb;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceVOIPUserAdd2
 */
public class ServiceVOIPUserAdd2Test {
    private final ServiceVOIPUserAdd2 model = new ServiceVOIPUserAdd2();

    /**
     * Model tests for ServiceVOIPUserAdd2
     */
    @Test
    public void testServiceVOIPUserAdd2() {
        // TODO: test ServiceVOIPUserAdd2
    }

    /**
     * Test the property 'callForward'
     */
    @Test
    public void callForwardTest() {
        // TODO: test callForward
    }

    /**
     * Test the property 'callRecording'
     */
    @Test
    public void callRecordingTest() {
        // TODO: test callRecording
    }

    /**
     * Test the property 'callerId'
     */
    @Test
    public void callerIdTest() {
        // TODO: test callerId
    }

    /**
     * Test the property 'doNotDisturb'
     */
    @Test
    public void doNotDisturbTest() {
        // TODO: test doNotDisturb
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'musicOnHold'
     */
    @Test
    public void musicOnHoldTest() {
        // TODO: test musicOnHold
    }

    /**
     * Test the property 'presenceId'
     */
    @Test
    public void presenceIdTest() {
        // TODO: test presenceId
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'verified'
     */
    @Test
    public void verifiedTest() {
        // TODO: test verified
    }

}
