/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ModelsVOIPAccountMusicOnHold;
import org.openapitools.client.model.ModelsVOIPAccountOutputFullCallerid;
import org.openapitools.client.model.ModelsVOIPSharedDoNotDisturb;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceVOIPAccountAddData
 */
public class ServiceVOIPAccountAddDataTest {
    private final ServiceVOIPAccountAddData model = new ServiceVOIPAccountAddData();

    /**
     * Model tests for ServiceVOIPAccountAddData
     */
    @Test
    public void testServiceVOIPAccountAddData() {
        // TODO: test ServiceVOIPAccountAddData
    }

    /**
     * Test the property 'callerId'
     */
    @Test
    public void callerIdTest() {
        // TODO: test callerId
    }

    /**
     * Test the property 'doNotDisturb'
     */
    @Test
    public void doNotDisturbTest() {
        // TODO: test doNotDisturb
    }

    /**
     * Test the property 'musicOnHold'
     */
    @Test
    public void musicOnHoldTest() {
        // TODO: test musicOnHold
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'realm'
     */
    @Test
    public void realmTest() {
        // TODO: test realm
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

}
