/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.client.model.ServiceE911LocationURILegacyData;
import org.openapitools.client.model.ServiceE911LocationURIStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceE911LocationURI
 */
public class ServiceE911LocationURITest {
    private final ServiceE911LocationURI model = new ServiceE911LocationURI();

    /**
     * Model tests for ServiceE911LocationURI
     */
    @Test
    public void testServiceE911LocationURI() {
        // TODO: test ServiceE911LocationURI
    }

    /**
     * Test the property 'activatedTime'
     */
    @Test
    public void activatedTimeTest() {
        // TODO: test activatedTime
    }

    /**
     * Test the property 'address1'
     */
    @Test
    public void address1Test() {
        // TODO: test address1
    }

    /**
     * Test the property 'address2'
     */
    @Test
    public void address2Test() {
        // TODO: test address2
    }

    /**
     * Test the property 'callerName'
     */
    @Test
    public void callerNameTest() {
        // TODO: test callerName
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'community'
     */
    @Test
    public void communityTest() {
        // TODO: test community
    }

    /**
     * Test the property 'customerOrderID'
     */
    @Test
    public void customerOrderIDTest() {
        // TODO: test customerOrderID
    }

    /**
     * Test the property 'latitude'
     */
    @Test
    public void latitudeTest() {
        // TODO: test latitude
    }

    /**
     * Test the property 'legacyData'
     */
    @Test
    public void legacyDataTest() {
        // TODO: test legacyData
    }

    /**
     * Test the property 'locationID'
     */
    @Test
    public void locationIDTest() {
        // TODO: test locationID
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    public void longitudeTest() {
        // TODO: test longitude
    }

    /**
     * Test the property 'plusFour'
     */
    @Test
    public void plusFourTest() {
        // TODO: test plusFour
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    public void updateTimeTest() {
        // TODO: test updateTime
    }

}
