/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceCdrOutputShort
 */
public class ServiceCdrOutputShortTest {
    private final ServiceCdrOutputShort model = new ServiceCdrOutputShort();

    /**
     * Model tests for ServiceCdrOutputShort
     */
    @Test
    public void testServiceCdrOutputShort() {
        // TODO: test ServiceCdrOutputShort
    }

    /**
     * Test the property 'authorizingId'
     */
    @Test
    public void authorizingIdTest() {
        // TODO: test authorizingId
    }

    /**
     * Test the property 'billingSeconds'
     */
    @Test
    public void billingSecondsTest() {
        // TODO: test billingSeconds
    }

    /**
     * Test the property 'bridgeId'
     */
    @Test
    public void bridgeIdTest() {
        // TODO: test bridgeId
    }

    /**
     * Test the property 'callId'
     */
    @Test
    public void callIdTest() {
        // TODO: test callId
    }

    /**
     * Test the property 'callPriority'
     */
    @Test
    public void callPriorityTest() {
        // TODO: test callPriority
    }

    /**
     * Test the property 'callType'
     */
    @Test
    public void callTypeTest() {
        // TODO: test callType
    }

    /**
     * Test the property 'calleeIdName'
     */
    @Test
    public void calleeIdNameTest() {
        // TODO: test calleeIdName
    }

    /**
     * Test the property 'calleeIdNumber'
     */
    @Test
    public void calleeIdNumberTest() {
        // TODO: test calleeIdNumber
    }

    /**
     * Test the property 'callerIdName'
     */
    @Test
    public void callerIdNameTest() {
        // TODO: test callerIdName
    }

    /**
     * Test the property 'callerIdNumber'
     */
    @Test
    public void callerIdNumberTest() {
        // TODO: test callerIdNumber
    }

    /**
     * Test the property 'callingFrom'
     */
    @Test
    public void callingFromTest() {
        // TODO: test callingFrom
    }

    /**
     * Test the property 'cost'
     */
    @Test
    public void costTest() {
        // TODO: test cost
    }

    /**
     * Test the property 'dialedNumber'
     */
    @Test
    public void dialedNumberTest() {
        // TODO: test dialedNumber
    }

    /**
     * Test the property 'direction'
     */
    @Test
    public void directionTest() {
        // TODO: test direction
    }

    /**
     * Test the property 'durationSeconds'
     */
    @Test
    public void durationSecondsTest() {
        // TODO: test durationSeconds
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'hangupCause'
     */
    @Test
    public void hangupCauseTest() {
        // TODO: test hangupCause
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'interactionId'
     */
    @Test
    public void interactionIdTest() {
        // TODO: test interactionId
    }

    /**
     * Test the property 'mediaRecordings'
     */
    @Test
    public void mediaRecordingsTest() {
        // TODO: test mediaRecordings
    }

    /**
     * Test the property 'mediaServer'
     */
    @Test
    public void mediaServerTest() {
        // TODO: test mediaServer
    }

    /**
     * Test the property 'otherLegCallId'
     */
    @Test
    public void otherLegCallIdTest() {
        // TODO: test otherLegCallId
    }

    /**
     * Test the property 'ownerId'
     */
    @Test
    public void ownerIdTest() {
        // TODO: test ownerId
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'rateName'
     */
    @Test
    public void rateNameTest() {
        // TODO: test rateName
    }

    /**
     * Test the property 'recordingUrl'
     */
    @Test
    public void recordingUrlTest() {
        // TODO: test recordingUrl
    }

    /**
     * Test the property 'request'
     */
    @Test
    public void requestTest() {
        // TODO: test request
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'timestampDatetime'
     */
    @Test
    public void timestampDatetimeTest() {
        // TODO: test timestampDatetime
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

}
