/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceCallRecordingOutput
 */
public class ServiceCallRecordingOutputTest {
    private final ServiceCallRecordingOutput model = new ServiceCallRecordingOutput();

    /**
     * Model tests for ServiceCallRecordingOutput
     */
    @Test
    public void testServiceCallRecordingOutput() {
        // TODO: test ServiceCallRecordingOutput
    }

    /**
     * Test the property 'callId'
     */
    @Test
    public void callIdTest() {
        // TODO: test callId
    }

    /**
     * Test the property 'calleeIdName'
     */
    @Test
    public void calleeIdNameTest() {
        // TODO: test calleeIdName
    }

    /**
     * Test the property 'calleeIdNumber'
     */
    @Test
    public void calleeIdNumberTest() {
        // TODO: test calleeIdNumber
    }

    /**
     * Test the property 'callerIdName'
     */
    @Test
    public void callerIdNameTest() {
        // TODO: test callerIdName
    }

    /**
     * Test the property 'callerIdNumber'
     */
    @Test
    public void callerIdNumberTest() {
        // TODO: test callerIdNumber
    }

    /**
     * Test the property 'cdrId'
     */
    @Test
    public void cdrIdTest() {
        // TODO: test cdrId
    }

    /**
     * Test the property 'contentType'
     */
    @Test
    public void contentTypeTest() {
        // TODO: test contentType
    }

    /**
     * Test the property 'customChannelVars'
     */
    @Test
    public void customChannelVarsTest() {
        // TODO: test customChannelVars
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'direction'
     */
    @Test
    public void directionTest() {
        // TODO: test direction
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'durationMs'
     */
    @Test
    public void durationMsTest() {
        // TODO: test durationMs
    }

    /**
     * Test the property 'endpointId'
     */
    @Test
    public void endpointIdTest() {
        // TODO: test endpointId
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'interactionId'
     */
    @Test
    public void interactionIdTest() {
        // TODO: test interactionId
    }

    /**
     * Test the property 'mediaSource'
     */
    @Test
    public void mediaSourceTest() {
        // TODO: test mediaSource
    }

    /**
     * Test the property 'mediaType'
     */
    @Test
    public void mediaTypeTest() {
        // TODO: test mediaType
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'origin'
     */
    @Test
    public void originTest() {
        // TODO: test origin
    }

    /**
     * Test the property 'ownerId'
     */
    @Test
    public void ownerIdTest() {
        // TODO: test ownerId
    }

    /**
     * Test the property 'request'
     */
    @Test
    public void requestTest() {
        // TODO: test request
    }

    /**
     * Test the property 'sourceType'
     */
    @Test
    public void sourceTypeTest() {
        // TODO: test sourceType
    }

    /**
     * Test the property 'start'
     */
    @Test
    public void startTest() {
        // TODO: test start
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
