/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceVOIPCallQueueEnableMembershipData
 */
public class ServiceVOIPCallQueueEnableMembershipDataTest {
    private final ServiceVOIPCallQueueEnableMembershipData model = new ServiceVOIPCallQueueEnableMembershipData();

    /**
     * Model tests for ServiceVOIPCallQueueEnableMembershipData
     */
    @Test
    public void testServiceVOIPCallQueueEnableMembershipData() {
        // TODO: test ServiceVOIPCallQueueEnableMembershipData
    }

    /**
     * Test the property 'acceptCharges'
     */
    @Test
    public void acceptChargesTest() {
        // TODO: test acceptCharges
    }

}
