/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ModelCallMonthlySummary
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ModelCallMonthlySummary {
  public static final String SERIALIZED_NAME_ACCOUNT_ID = "account_id";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  @javax.annotation.Nullable
  private String accountId;

  public static final String SERIALIZED_NAME_CALL_MONTH = "call_month";
  @SerializedName(SERIALIZED_NAME_CALL_MONTH)
  @javax.annotation.Nullable
  private Integer callMonth;

  public static final String SERIALIZED_NAME_CALL_TYPE = "call_type";
  @SerializedName(SERIALIZED_NAME_CALL_TYPE)
  @javax.annotation.Nullable
  private String callType;

  public static final String SERIALIZED_NAME_CALL_YEAR = "call_year";
  @SerializedName(SERIALIZED_NAME_CALL_YEAR)
  @javax.annotation.Nullable
  private Integer callYear;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private String createdAt;

  public static final String SERIALIZED_NAME_TOTAL_CALL_DURATION = "total_call_duration";
  @SerializedName(SERIALIZED_NAME_TOTAL_CALL_DURATION)
  @javax.annotation.Nullable
  private String totalCallDuration;

  public ModelCallMonthlySummary() {
  }

  public ModelCallMonthlySummary accountId(@javax.annotation.Nullable String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   * @return accountId
   */
  @javax.annotation.Nullable
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(@javax.annotation.Nullable String accountId) {
    this.accountId = accountId;
  }


  public ModelCallMonthlySummary callMonth(@javax.annotation.Nullable Integer callMonth) {
    this.callMonth = callMonth;
    return this;
  }

  /**
   * Get callMonth
   * @return callMonth
   */
  @javax.annotation.Nullable
  public Integer getCallMonth() {
    return callMonth;
  }

  public void setCallMonth(@javax.annotation.Nullable Integer callMonth) {
    this.callMonth = callMonth;
  }


  public ModelCallMonthlySummary callType(@javax.annotation.Nullable String callType) {
    this.callType = callType;
    return this;
  }

  /**
   * Get callType
   * @return callType
   */
  @javax.annotation.Nullable
  public String getCallType() {
    return callType;
  }

  public void setCallType(@javax.annotation.Nullable String callType) {
    this.callType = callType;
  }


  public ModelCallMonthlySummary callYear(@javax.annotation.Nullable Integer callYear) {
    this.callYear = callYear;
    return this;
  }

  /**
   * Get callYear
   * @return callYear
   */
  @javax.annotation.Nullable
  public Integer getCallYear() {
    return callYear;
  }

  public void setCallYear(@javax.annotation.Nullable Integer callYear) {
    this.callYear = callYear;
  }


  public ModelCallMonthlySummary createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public ModelCallMonthlySummary totalCallDuration(@javax.annotation.Nullable String totalCallDuration) {
    this.totalCallDuration = totalCallDuration;
    return this;
  }

  /**
   * Get totalCallDuration
   * @return totalCallDuration
   */
  @javax.annotation.Nullable
  public String getTotalCallDuration() {
    return totalCallDuration;
  }

  public void setTotalCallDuration(@javax.annotation.Nullable String totalCallDuration) {
    this.totalCallDuration = totalCallDuration;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelCallMonthlySummary modelCallMonthlySummary = (ModelCallMonthlySummary) o;
    return Objects.equals(this.accountId, modelCallMonthlySummary.accountId) &&
        Objects.equals(this.callMonth, modelCallMonthlySummary.callMonth) &&
        Objects.equals(this.callType, modelCallMonthlySummary.callType) &&
        Objects.equals(this.callYear, modelCallMonthlySummary.callYear) &&
        Objects.equals(this.createdAt, modelCallMonthlySummary.createdAt) &&
        Objects.equals(this.totalCallDuration, modelCallMonthlySummary.totalCallDuration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, callMonth, callType, callYear, createdAt, totalCallDuration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelCallMonthlySummary {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    callMonth: ").append(toIndentedString(callMonth)).append("\n");
    sb.append("    callType: ").append(toIndentedString(callType)).append("\n");
    sb.append("    callYear: ").append(toIndentedString(callYear)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    totalCallDuration: ").append(toIndentedString(totalCallDuration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("account_id");
    openapiFields.add("call_month");
    openapiFields.add("call_type");
    openapiFields.add("call_year");
    openapiFields.add("created_at");
    openapiFields.add("total_call_duration");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ModelCallMonthlySummary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ModelCallMonthlySummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ModelCallMonthlySummary is not found in the empty JSON string", ModelCallMonthlySummary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ModelCallMonthlySummary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ModelCallMonthlySummary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("account_id") != null && !jsonObj.get("account_id").isJsonNull()) && !jsonObj.get("account_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `account_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("account_id").toString()));
      }
      if ((jsonObj.get("call_type") != null && !jsonObj.get("call_type").isJsonNull()) && !jsonObj.get("call_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `call_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("call_type").toString()));
      }
      if ((jsonObj.get("created_at") != null && !jsonObj.get("created_at").isJsonNull()) && !jsonObj.get("created_at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `created_at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_at").toString()));
      }
      if ((jsonObj.get("total_call_duration") != null && !jsonObj.get("total_call_duration").isJsonNull()) && !jsonObj.get("total_call_duration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `total_call_duration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("total_call_duration").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ModelCallMonthlySummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ModelCallMonthlySummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ModelCallMonthlySummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ModelCallMonthlySummary.class));

       return (TypeAdapter<T>) new TypeAdapter<ModelCallMonthlySummary>() {
           @Override
           public void write(JsonWriter out, ModelCallMonthlySummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ModelCallMonthlySummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ModelCallMonthlySummary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ModelCallMonthlySummary
   * @throws IOException if the JSON string is invalid with respect to ModelCallMonthlySummary
   */
  public static ModelCallMonthlySummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ModelCallMonthlySummary.class);
  }

  /**
   * Convert an instance of ModelCallMonthlySummary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

