/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ServiceVoicemailMedia;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ServiceVoicemailOutputFull
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceVoicemailOutputFull {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_MAILBOX = "mailbox";
  @SerializedName(SERIALIZED_NAME_MAILBOX)
  @javax.annotation.Nullable
  private String mailbox;

  public static final String SERIALIZED_NAME_MEDIA = "media";
  @SerializedName(SERIALIZED_NAME_MEDIA)
  @javax.annotation.Nullable
  private ServiceVoicemailMedia media;

  public static final String SERIALIZED_NAME_MEDIA_EXTENSION = "media_extension";
  @SerializedName(SERIALIZED_NAME_MEDIA_EXTENSION)
  @javax.annotation.Nullable
  private String mediaExtension;

  public static final String SERIALIZED_NAME_MESSAGES = "messages";
  @SerializedName(SERIALIZED_NAME_MESSAGES)
  @javax.annotation.Nullable
  private Integer messages;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_OWNER_ID = "owner_id";
  @SerializedName(SERIALIZED_NAME_OWNER_ID)
  @javax.annotation.Nullable
  private String ownerId;

  public static final String SERIALIZED_NAME_PIN = "pin";
  @SerializedName(SERIALIZED_NAME_PIN)
  @javax.annotation.Nullable
  private String pin;

  public static final String SERIALIZED_NAME_REQUIRE_PIN = "require_pin";
  @SerializedName(SERIALIZED_NAME_REQUIRE_PIN)
  @javax.annotation.Nullable
  private Boolean requirePin;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nullable
  private String timezone;

  public ServiceVoicemailOutputFull() {
  }

  public ServiceVoicemailOutputFull id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public ServiceVoicemailOutputFull mailbox(@javax.annotation.Nullable String mailbox) {
    this.mailbox = mailbox;
    return this;
  }

  /**
   * Get mailbox
   * @return mailbox
   */
  @javax.annotation.Nullable
  public String getMailbox() {
    return mailbox;
  }

  public void setMailbox(@javax.annotation.Nullable String mailbox) {
    this.mailbox = mailbox;
  }


  public ServiceVoicemailOutputFull media(@javax.annotation.Nullable ServiceVoicemailMedia media) {
    this.media = media;
    return this;
  }

  /**
   * Get media
   * @return media
   */
  @javax.annotation.Nullable
  public ServiceVoicemailMedia getMedia() {
    return media;
  }

  public void setMedia(@javax.annotation.Nullable ServiceVoicemailMedia media) {
    this.media = media;
  }


  public ServiceVoicemailOutputFull mediaExtension(@javax.annotation.Nullable String mediaExtension) {
    this.mediaExtension = mediaExtension;
    return this;
  }

  /**
   * Get mediaExtension
   * @return mediaExtension
   */
  @javax.annotation.Nullable
  public String getMediaExtension() {
    return mediaExtension;
  }

  public void setMediaExtension(@javax.annotation.Nullable String mediaExtension) {
    this.mediaExtension = mediaExtension;
  }


  public ServiceVoicemailOutputFull messages(@javax.annotation.Nullable Integer messages) {
    this.messages = messages;
    return this;
  }

  /**
   * Get messages
   * @return messages
   */
  @javax.annotation.Nullable
  public Integer getMessages() {
    return messages;
  }

  public void setMessages(@javax.annotation.Nullable Integer messages) {
    this.messages = messages;
  }


  public ServiceVoicemailOutputFull name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public ServiceVoicemailOutputFull ownerId(@javax.annotation.Nullable String ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  /**
   * Get ownerId
   * @return ownerId
   */
  @javax.annotation.Nullable
  public String getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(@javax.annotation.Nullable String ownerId) {
    this.ownerId = ownerId;
  }


  public ServiceVoicemailOutputFull pin(@javax.annotation.Nullable String pin) {
    this.pin = pin;
    return this;
  }

  /**
   * Get pin
   * @return pin
   */
  @javax.annotation.Nullable
  public String getPin() {
    return pin;
  }

  public void setPin(@javax.annotation.Nullable String pin) {
    this.pin = pin;
  }


  public ServiceVoicemailOutputFull requirePin(@javax.annotation.Nullable Boolean requirePin) {
    this.requirePin = requirePin;
    return this;
  }

  /**
   * Get requirePin
   * @return requirePin
   */
  @javax.annotation.Nullable
  public Boolean getRequirePin() {
    return requirePin;
  }

  public void setRequirePin(@javax.annotation.Nullable Boolean requirePin) {
    this.requirePin = requirePin;
  }


  public ServiceVoicemailOutputFull timezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * Get timezone
   * @return timezone
   */
  @javax.annotation.Nullable
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVoicemailOutputFull serviceVoicemailOutputFull = (ServiceVoicemailOutputFull) o;
    return Objects.equals(this.id, serviceVoicemailOutputFull.id) &&
        Objects.equals(this.mailbox, serviceVoicemailOutputFull.mailbox) &&
        Objects.equals(this.media, serviceVoicemailOutputFull.media) &&
        Objects.equals(this.mediaExtension, serviceVoicemailOutputFull.mediaExtension) &&
        Objects.equals(this.messages, serviceVoicemailOutputFull.messages) &&
        Objects.equals(this.name, serviceVoicemailOutputFull.name) &&
        Objects.equals(this.ownerId, serviceVoicemailOutputFull.ownerId) &&
        Objects.equals(this.pin, serviceVoicemailOutputFull.pin) &&
        Objects.equals(this.requirePin, serviceVoicemailOutputFull.requirePin) &&
        Objects.equals(this.timezone, serviceVoicemailOutputFull.timezone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, mailbox, media, mediaExtension, messages, name, ownerId, pin, requirePin, timezone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVoicemailOutputFull {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mailbox: ").append(toIndentedString(mailbox)).append("\n");
    sb.append("    media: ").append(toIndentedString(media)).append("\n");
    sb.append("    mediaExtension: ").append(toIndentedString(mediaExtension)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("    requirePin: ").append(toIndentedString(requirePin)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("mailbox");
    openapiFields.add("media");
    openapiFields.add("media_extension");
    openapiFields.add("messages");
    openapiFields.add("name");
    openapiFields.add("owner_id");
    openapiFields.add("pin");
    openapiFields.add("require_pin");
    openapiFields.add("timezone");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceVoicemailOutputFull
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceVoicemailOutputFull.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServiceVoicemailOutputFull is not found in the empty JSON string", ServiceVoicemailOutputFull.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceVoicemailOutputFull.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServiceVoicemailOutputFull` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("mailbox") != null && !jsonObj.get("mailbox").isJsonNull()) && !jsonObj.get("mailbox").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mailbox` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mailbox").toString()));
      }
      // validate the optional field `media`
      if (jsonObj.get("media") != null && !jsonObj.get("media").isJsonNull()) {
        ServiceVoicemailMedia.validateJsonElement(jsonObj.get("media"));
      }
      if ((jsonObj.get("media_extension") != null && !jsonObj.get("media_extension").isJsonNull()) && !jsonObj.get("media_extension").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `media_extension` to be a primitive type in the JSON string but got `%s`", jsonObj.get("media_extension").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("owner_id") != null && !jsonObj.get("owner_id").isJsonNull()) && !jsonObj.get("owner_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `owner_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("owner_id").toString()));
      }
      if ((jsonObj.get("pin") != null && !jsonObj.get("pin").isJsonNull()) && !jsonObj.get("pin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pin").toString()));
      }
      if ((jsonObj.get("timezone") != null && !jsonObj.get("timezone").isJsonNull()) && !jsonObj.get("timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timezone").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceVoicemailOutputFull.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceVoicemailOutputFull' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceVoicemailOutputFull> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceVoicemailOutputFull.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceVoicemailOutputFull>() {
           @Override
           public void write(JsonWriter out, ServiceVoicemailOutputFull value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceVoicemailOutputFull read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceVoicemailOutputFull given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceVoicemailOutputFull
   * @throws IOException if the JSON string is invalid with respect to ServiceVoicemailOutputFull
   */
  public static ServiceVoicemailOutputFull fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceVoicemailOutputFull.class);
  }

  /**
   * Convert an instance of ServiceVoicemailOutputFull to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

