/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ServiceSystemStatusCPAASService
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceSystemStatusCPAASService {
  public static final String SERIALIZED_NAME_BACKEND = "backend";
  @SerializedName(SERIALIZED_NAME_BACKEND)
  @javax.annotation.Nullable
  private String backend;

  public static final String SERIALIZED_NAME_PORTAL = "portal";
  @SerializedName(SERIALIZED_NAME_PORTAL)
  @javax.annotation.Nullable
  private String portal;

  public static final String SERIALIZED_NAME_SERVER = "server";
  @SerializedName(SERIALIZED_NAME_SERVER)
  @javax.annotation.Nullable
  private String server;

  public ServiceSystemStatusCPAASService() {
  }

  public ServiceSystemStatusCPAASService backend(@javax.annotation.Nullable String backend) {
    this.backend = backend;
    return this;
  }

  /**
   * Get backend
   * @return backend
   */
  @javax.annotation.Nullable
  public String getBackend() {
    return backend;
  }

  public void setBackend(@javax.annotation.Nullable String backend) {
    this.backend = backend;
  }


  public ServiceSystemStatusCPAASService portal(@javax.annotation.Nullable String portal) {
    this.portal = portal;
    return this;
  }

  /**
   * Get portal
   * @return portal
   */
  @javax.annotation.Nullable
  public String getPortal() {
    return portal;
  }

  public void setPortal(@javax.annotation.Nullable String portal) {
    this.portal = portal;
  }


  public ServiceSystemStatusCPAASService server(@javax.annotation.Nullable String server) {
    this.server = server;
    return this;
  }

  /**
   * Get server
   * @return server
   */
  @javax.annotation.Nullable
  public String getServer() {
    return server;
  }

  public void setServer(@javax.annotation.Nullable String server) {
    this.server = server;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceSystemStatusCPAASService serviceSystemStatusCPAASService = (ServiceSystemStatusCPAASService) o;
    return Objects.equals(this.backend, serviceSystemStatusCPAASService.backend) &&
        Objects.equals(this.portal, serviceSystemStatusCPAASService.portal) &&
        Objects.equals(this.server, serviceSystemStatusCPAASService.server);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backend, portal, server);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceSystemStatusCPAASService {\n");
    sb.append("    backend: ").append(toIndentedString(backend)).append("\n");
    sb.append("    portal: ").append(toIndentedString(portal)).append("\n");
    sb.append("    server: ").append(toIndentedString(server)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("backend", "portal", "server"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceSystemStatusCPAASService
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceSystemStatusCPAASService.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServiceSystemStatusCPAASService is not found in the empty JSON string", ServiceSystemStatusCPAASService.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceSystemStatusCPAASService.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServiceSystemStatusCPAASService` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("backend") != null && !jsonObj.get("backend").isJsonNull()) && !jsonObj.get("backend").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `backend` to be a primitive type in the JSON string but got `%s`", jsonObj.get("backend").toString()));
      }
      if ((jsonObj.get("portal") != null && !jsonObj.get("portal").isJsonNull()) && !jsonObj.get("portal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `portal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("portal").toString()));
      }
      if ((jsonObj.get("server") != null && !jsonObj.get("server").isJsonNull()) && !jsonObj.get("server").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `server` to be a primitive type in the JSON string but got `%s`", jsonObj.get("server").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceSystemStatusCPAASService.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceSystemStatusCPAASService' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceSystemStatusCPAASService> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceSystemStatusCPAASService.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceSystemStatusCPAASService>() {
           @Override
           public void write(JsonWriter out, ServiceSystemStatusCPAASService value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceSystemStatusCPAASService read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceSystemStatusCPAASService given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceSystemStatusCPAASService
   * @throws IOException if the JSON string is invalid with respect to ServiceSystemStatusCPAASService
   */
  public static ServiceSystemStatusCPAASService fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceSystemStatusCPAASService.class);
  }

  /**
   * Convert an instance of ServiceSystemStatusCPAASService to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

