/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ServiceStoragePlanDatabaseAttachment;
import org.openapitools.client.model.ServiceStoragePlanDatabaseProperties;
import org.openapitools.client.model.ServiceStoragePlanDatabaseTypes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ServiceStoragePlanDatabase
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceStoragePlanDatabase {
  public static final String SERIALIZED_NAME_ATTACHMENTS = "attachments";
  @SerializedName(SERIALIZED_NAME_ATTACHMENTS)
  @javax.annotation.Nullable
  private ServiceStoragePlanDatabaseAttachment attachments;

  public static final String SERIALIZED_NAME_CONNECTION = "connection";
  @SerializedName(SERIALIZED_NAME_CONNECTION)
  @javax.annotation.Nullable
  private String connection;

  public static final String SERIALIZED_NAME_DATABASE = "database";
  @SerializedName(SERIALIZED_NAME_DATABASE)
  @javax.annotation.Nullable
  private ServiceStoragePlanDatabaseProperties database;

  public static final String SERIALIZED_NAME_TYPES = "types";
  @SerializedName(SERIALIZED_NAME_TYPES)
  @javax.annotation.Nullable
  private ServiceStoragePlanDatabaseTypes types;

  public ServiceStoragePlanDatabase() {
  }

  public ServiceStoragePlanDatabase attachments(@javax.annotation.Nullable ServiceStoragePlanDatabaseAttachment attachments) {
    this.attachments = attachments;
    return this;
  }

  /**
   * Get attachments
   * @return attachments
   */
  @javax.annotation.Nullable
  public ServiceStoragePlanDatabaseAttachment getAttachments() {
    return attachments;
  }

  public void setAttachments(@javax.annotation.Nullable ServiceStoragePlanDatabaseAttachment attachments) {
    this.attachments = attachments;
  }


  public ServiceStoragePlanDatabase connection(@javax.annotation.Nullable String connection) {
    this.connection = connection;
    return this;
  }

  /**
   * Get connection
   * @return connection
   */
  @javax.annotation.Nullable
  public String getConnection() {
    return connection;
  }

  public void setConnection(@javax.annotation.Nullable String connection) {
    this.connection = connection;
  }


  public ServiceStoragePlanDatabase database(@javax.annotation.Nullable ServiceStoragePlanDatabaseProperties database) {
    this.database = database;
    return this;
  }

  /**
   * Get database
   * @return database
   */
  @javax.annotation.Nullable
  public ServiceStoragePlanDatabaseProperties getDatabase() {
    return database;
  }

  public void setDatabase(@javax.annotation.Nullable ServiceStoragePlanDatabaseProperties database) {
    this.database = database;
  }


  public ServiceStoragePlanDatabase types(@javax.annotation.Nullable ServiceStoragePlanDatabaseTypes types) {
    this.types = types;
    return this;
  }

  /**
   * Get types
   * @return types
   */
  @javax.annotation.Nullable
  public ServiceStoragePlanDatabaseTypes getTypes() {
    return types;
  }

  public void setTypes(@javax.annotation.Nullable ServiceStoragePlanDatabaseTypes types) {
    this.types = types;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceStoragePlanDatabase serviceStoragePlanDatabase = (ServiceStoragePlanDatabase) o;
    return Objects.equals(this.attachments, serviceStoragePlanDatabase.attachments) &&
        Objects.equals(this.connection, serviceStoragePlanDatabase.connection) &&
        Objects.equals(this.database, serviceStoragePlanDatabase.database) &&
        Objects.equals(this.types, serviceStoragePlanDatabase.types);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachments, connection, database, types);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceStoragePlanDatabase {\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    connection: ").append(toIndentedString(connection)).append("\n");
    sb.append("    database: ").append(toIndentedString(database)).append("\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("attachments", "connection", "database", "types"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceStoragePlanDatabase
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceStoragePlanDatabase.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServiceStoragePlanDatabase is not found in the empty JSON string", ServiceStoragePlanDatabase.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceStoragePlanDatabase.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServiceStoragePlanDatabase` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `attachments`
      if (jsonObj.get("attachments") != null && !jsonObj.get("attachments").isJsonNull()) {
        ServiceStoragePlanDatabaseAttachment.validateJsonElement(jsonObj.get("attachments"));
      }
      if ((jsonObj.get("connection") != null && !jsonObj.get("connection").isJsonNull()) && !jsonObj.get("connection").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `connection` to be a primitive type in the JSON string but got `%s`", jsonObj.get("connection").toString()));
      }
      // validate the optional field `database`
      if (jsonObj.get("database") != null && !jsonObj.get("database").isJsonNull()) {
        ServiceStoragePlanDatabaseProperties.validateJsonElement(jsonObj.get("database"));
      }
      // validate the optional field `types`
      if (jsonObj.get("types") != null && !jsonObj.get("types").isJsonNull()) {
        ServiceStoragePlanDatabaseTypes.validateJsonElement(jsonObj.get("types"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceStoragePlanDatabase.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceStoragePlanDatabase' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceStoragePlanDatabase> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceStoragePlanDatabase.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceStoragePlanDatabase>() {
           @Override
           public void write(JsonWriter out, ServiceStoragePlanDatabase value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceStoragePlanDatabase read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceStoragePlanDatabase given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceStoragePlanDatabase
   * @throws IOException if the JSON string is invalid with respect to ServiceStoragePlanDatabase
   */
  public static ServiceStoragePlanDatabase fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceStoragePlanDatabase.class);
  }

  /**
   * Convert an instance of ServiceStoragePlanDatabase to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

