/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ServiceCallflowOutputShort;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ServiceDocsCallflowGetAll
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceDocsCallflowGetAll {
  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nullable
  private ServiceCallflowOutputShort data;

  public static final String SERIALIZED_NAME_NEXT_START_KEY = "next_start_key";
  @SerializedName(SERIALIZED_NAME_NEXT_START_KEY)
  @javax.annotation.Nullable
  private String nextStartKey;

  public static final String SERIALIZED_NAME_PAGE_SIZE = "page_size";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  @javax.annotation.Nullable
  private Integer pageSize;

  public static final String SERIALIZED_NAME_REQUEST_ID = "request_id";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID)
  @javax.annotation.Nullable
  private String requestId;

  public static final String SERIALIZED_NAME_START_KEY = "start_key";
  @SerializedName(SERIALIZED_NAME_START_KEY)
  @javax.annotation.Nullable
  private String startKey;

  public static final String SERIALIZED_NAME_STATUS_CODE = "status_code";
  @SerializedName(SERIALIZED_NAME_STATUS_CODE)
  @javax.annotation.Nullable
  private Integer statusCode;

  public ServiceDocsCallflowGetAll() {
  }

  public ServiceDocsCallflowGetAll data(@javax.annotation.Nullable ServiceCallflowOutputShort data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  public ServiceCallflowOutputShort getData() {
    return data;
  }

  public void setData(@javax.annotation.Nullable ServiceCallflowOutputShort data) {
    this.data = data;
  }


  public ServiceDocsCallflowGetAll nextStartKey(@javax.annotation.Nullable String nextStartKey) {
    this.nextStartKey = nextStartKey;
    return this;
  }

  /**
   * List Pagination: Used to get the next page of results. Will not exist if this is the last page.
   * @return nextStartKey
   */
  @javax.annotation.Nullable
  public String getNextStartKey() {
    return nextStartKey;
  }

  public void setNextStartKey(@javax.annotation.Nullable String nextStartKey) {
    this.nextStartKey = nextStartKey;
  }


  public ServiceDocsCallflowGetAll pageSize(@javax.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

  /**
   * List Pagination: The number of results returned in this page
   * @return pageSize
   */
  @javax.annotation.Nullable
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(@javax.annotation.Nullable Integer pageSize) {
    this.pageSize = pageSize;
  }


  public ServiceDocsCallflowGetAll requestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Unique id for each request
   * @return requestId
   */
  @javax.annotation.Nullable
  public String getRequestId() {
    return requestId;
  }

  public void setRequestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
  }


  public ServiceDocsCallflowGetAll startKey(@javax.annotation.Nullable String startKey) {
    this.startKey = startKey;
    return this;
  }

  /**
   * List Pagination: Code for paged results
   * @return startKey
   */
  @javax.annotation.Nullable
  public String getStartKey() {
    return startKey;
  }

  public void setStartKey(@javax.annotation.Nullable String startKey) {
    this.startKey = startKey;
  }


  public ServiceDocsCallflowGetAll statusCode(@javax.annotation.Nullable Integer statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  /**
   * HTTP response status code
   * @return statusCode
   */
  @javax.annotation.Nullable
  public Integer getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(@javax.annotation.Nullable Integer statusCode) {
    this.statusCode = statusCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceDocsCallflowGetAll serviceDocsCallflowGetAll = (ServiceDocsCallflowGetAll) o;
    return Objects.equals(this.data, serviceDocsCallflowGetAll.data) &&
        Objects.equals(this.nextStartKey, serviceDocsCallflowGetAll.nextStartKey) &&
        Objects.equals(this.pageSize, serviceDocsCallflowGetAll.pageSize) &&
        Objects.equals(this.requestId, serviceDocsCallflowGetAll.requestId) &&
        Objects.equals(this.startKey, serviceDocsCallflowGetAll.startKey) &&
        Objects.equals(this.statusCode, serviceDocsCallflowGetAll.statusCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, nextStartKey, pageSize, requestId, startKey, statusCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceDocsCallflowGetAll {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    nextStartKey: ").append(toIndentedString(nextStartKey)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    startKey: ").append(toIndentedString(startKey)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("data", "next_start_key", "page_size", "request_id", "start_key", "status_code"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceDocsCallflowGetAll
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceDocsCallflowGetAll.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServiceDocsCallflowGetAll is not found in the empty JSON string", ServiceDocsCallflowGetAll.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceDocsCallflowGetAll.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServiceDocsCallflowGetAll` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `data`
      if (jsonObj.get("data") != null && !jsonObj.get("data").isJsonNull()) {
        ServiceCallflowOutputShort.validateJsonElement(jsonObj.get("data"));
      }
      if ((jsonObj.get("next_start_key") != null && !jsonObj.get("next_start_key").isJsonNull()) && !jsonObj.get("next_start_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `next_start_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("next_start_key").toString()));
      }
      if ((jsonObj.get("request_id") != null && !jsonObj.get("request_id").isJsonNull()) && !jsonObj.get("request_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `request_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("request_id").toString()));
      }
      if ((jsonObj.get("start_key") != null && !jsonObj.get("start_key").isJsonNull()) && !jsonObj.get("start_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `start_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("start_key").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceDocsCallflowGetAll.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceDocsCallflowGetAll' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceDocsCallflowGetAll> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceDocsCallflowGetAll.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceDocsCallflowGetAll>() {
           @Override
           public void write(JsonWriter out, ServiceDocsCallflowGetAll value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceDocsCallflowGetAll read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceDocsCallflowGetAll given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceDocsCallflowGetAll
   * @throws IOException if the JSON string is invalid with respect to ServiceDocsCallflowGetAll
   */
  public static ServiceDocsCallflowGetAll fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceDocsCallflowGetAll.class);
  }

  /**
   * Convert an instance of ServiceDocsCallflowGetAll to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

