/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TypesGeoLocation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class TypesGeoLocation {
  public static final String SERIALIZED_NAME_CONTINENT_CODE = "continentCode";
  @SerializedName(SERIALIZED_NAME_CONTINENT_CODE)
  @javax.annotation.Nullable
  private String continentCode;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "countryCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  @javax.annotation.Nullable
  private String countryCode;

  public static final String SERIALIZED_NAME_SUBDIVISION_CODE = "subdivisionCode";
  @SerializedName(SERIALIZED_NAME_SUBDIVISION_CODE)
  @javax.annotation.Nullable
  private String subdivisionCode;

  public TypesGeoLocation() {
  }

  public TypesGeoLocation continentCode(@javax.annotation.Nullable String continentCode) {
    this.continentCode = continentCode;
    return this;
  }

  /**
   * The two-letter code for the continent.  Amazon Route 53 supports the following continent codes:    - AF: Africa    - AN: Antarctica    - AS: Asia    - EU: Europe    - OC: Oceania    - NA: North America    - SA: South America  Constraint: Specifying ContinentCode with either CountryCode or SubdivisionCode returns an InvalidInput error.
   * @return continentCode
   */
  @javax.annotation.Nullable
  public String getContinentCode() {
    return continentCode;
  }

  public void setContinentCode(@javax.annotation.Nullable String continentCode) {
    this.continentCode = continentCode;
  }


  public TypesGeoLocation countryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * For geolocation resource record sets, the two-letter code for a country.  Amazon Route 53 uses the two-letter country codes that are specified in [ISO standard 3166-1 alpha-2].  Route 53 also supports the country code UA for Ukraine.  [ISO standard 3166-1 alpha-2]: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
   * @return countryCode
   */
  @javax.annotation.Nullable
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(@javax.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
  }


  public TypesGeoLocation subdivisionCode(@javax.annotation.Nullable String subdivisionCode) {
    this.subdivisionCode = subdivisionCode;
    return this;
  }

  /**
   * For geolocation resource record sets, the two-letter code for a state of the United States. Route 53 doesn&#39;t support any other values for SubdivisionCode . For a list of state abbreviations, see [Appendix B: Two–Letter State and Possession Abbreviations]on the United States Postal Service website.  If you specify subdivisioncode , you must also specify US for CountryCode .  [Appendix B: Two–Letter State and Possession Abbreviations]: https://pe.usps.com/text/pub28/28apb.htm
   * @return subdivisionCode
   */
  @javax.annotation.Nullable
  public String getSubdivisionCode() {
    return subdivisionCode;
  }

  public void setSubdivisionCode(@javax.annotation.Nullable String subdivisionCode) {
    this.subdivisionCode = subdivisionCode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TypesGeoLocation typesGeoLocation = (TypesGeoLocation) o;
    return Objects.equals(this.continentCode, typesGeoLocation.continentCode) &&
        Objects.equals(this.countryCode, typesGeoLocation.countryCode) &&
        Objects.equals(this.subdivisionCode, typesGeoLocation.subdivisionCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(continentCode, countryCode, subdivisionCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TypesGeoLocation {\n");
    sb.append("    continentCode: ").append(toIndentedString(continentCode)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    subdivisionCode: ").append(toIndentedString(subdivisionCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("continentCode", "countryCode", "subdivisionCode"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TypesGeoLocation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TypesGeoLocation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TypesGeoLocation is not found in the empty JSON string", TypesGeoLocation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TypesGeoLocation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TypesGeoLocation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("continentCode") != null && !jsonObj.get("continentCode").isJsonNull()) && !jsonObj.get("continentCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `continentCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("continentCode").toString()));
      }
      if ((jsonObj.get("countryCode") != null && !jsonObj.get("countryCode").isJsonNull()) && !jsonObj.get("countryCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `countryCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("countryCode").toString()));
      }
      if ((jsonObj.get("subdivisionCode") != null && !jsonObj.get("subdivisionCode").isJsonNull()) && !jsonObj.get("subdivisionCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subdivisionCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("subdivisionCode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TypesGeoLocation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TypesGeoLocation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TypesGeoLocation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TypesGeoLocation.class));

       return (TypeAdapter<T>) new TypeAdapter<TypesGeoLocation>() {
           @Override
           public void write(JsonWriter out, TypesGeoLocation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TypesGeoLocation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TypesGeoLocation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TypesGeoLocation
   * @throws IOException if the JSON string is invalid with respect to TypesGeoLocation
   */
  public static TypesGeoLocation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TypesGeoLocation.class);
  }

  /**
   * Convert an instance of TypesGeoLocation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

