/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CPAASError;
import org.openapitools.client.model.ServiceAPIResponse;
import org.openapitools.client.model.ServiceDocsCallQueueResponseShort;
import org.openapitools.client.model.ServiceDocsGetQueueRecipients;
import org.openapitools.client.model.ServiceVOIPCallQueueRecipientLoginLogoutData;
import org.openapitools.client.model.ServiceVOIPCallQueueRecipientStatusData;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CallQueueRecipientApi
 */
@Disabled
public class CallQueueRecipientApiTest {

    private final CallQueueRecipientApi api = new CallQueueRecipientApi();

    /**
     * Login as Recipient
     *
     * Agents must log in to receive calls. Depending on their membership, they can log in to one or more queues. (If an agent is a member of more than one queue, they will receive calls from all the queues they are a part of.)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountAccountIDLoginrecipientRecipientIDPostTest() throws ApiException {
        String accountID = null;
        String recipientID = null;
        ServiceVOIPCallQueueRecipientLoginLogoutData reqBody = null;
        ServiceDocsCallQueueResponseShort response = api.v1AccountAccountIDLoginrecipientRecipientIDPost(accountID, recipientID, reqBody);
        // TODO: test validations
    }

    /**
     * Change Recipient Status
     *
     * Get a list of all recipients in an account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountAccountIDQueuerecipientGetTest() throws ApiException {
        String accountID = null;
        ServiceDocsGetQueueRecipients response = api.v1AccountAccountIDQueuerecipientGet(accountID);
        // TODO: test validations
    }

    /**
     * Get Recipient List
     *
     * Change the status of a recipient to ready, away, etc.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1AccountAccountIDRecipientRecipientIDStatusPostTest() throws ApiException {
        String accountID = null;
        String recipientID = null;
        ServiceVOIPCallQueueRecipientStatusData reqBody = null;
        ServiceAPIResponse response = api.v1AccountAccountIDRecipientRecipientIDStatusPost(accountID, recipientID, reqBody);
        // TODO: test validations
    }

}
