/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CPAASError;
import org.openapitools.client.model.ServiceAdminUserAddData;
import org.openapitools.client.model.ServiceAdminUserEditData;
import org.openapitools.client.model.ServiceDocsAdminUserDelete;
import org.openapitools.client.model.ServiceDocsAdminUserGetAll;
import org.openapitools.client.model.ServiceDocsAdminUserGetSingle;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CPaaSManagementApi
 */
@Disabled
public class CPaaSManagementApiTest {

    private final CPaaSManagementApi api = new CPaaSManagementApi();

    /**
     * Get All CPaaS Users
     *
     * Retrieve a list of all CPaaS users in an account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MgmtUserGetTest() throws ApiException {
        Integer pageSize = null;
        String startKey = null;
        String sort = null;
        String email = null;
        String role = null;
        String firstName = null;
        String lastName = null;
        ServiceDocsAdminUserGetAll response = api.v1MgmtUserGet(pageSize, startKey, sort, email, role, firstName, lastName);
        // TODO: test validations
    }

    /**
     * Invite CPaaS User
     *
     * Link a new CPaaS user to an existing client account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MgmtUserPostTest() throws ApiException {
        ServiceAdminUserAddData reqBody = null;
        ServiceDocsAdminUserGetSingle response = api.v1MgmtUserPost(reqBody);
        // TODO: test validations
    }

    /**
     * Delete CPaaS User
     *
     * Delete a CPaaS user from the associated account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MgmtUserUserIDDeleteTest() throws ApiException {
        String userID = null;
        ServiceDocsAdminUserDelete response = api.v1MgmtUserUserIDDelete(userID);
        // TODO: test validations
    }

    /**
     * Get CPaaS User Details
     *
     * View details about each CPaaS user in an account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MgmtUserUserIDGetTest() throws ApiException {
        String userID = null;
        ServiceDocsAdminUserGetSingle response = api.v1MgmtUserUserIDGet(userID);
        // TODO: test validations
    }

    /**
     * Update CPaaS User Role
     *
     * Update a CPaaS user&#39;s role within a client&#39;s account.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1MgmtUserUserIDPutTest() throws ApiException {
        String userID = null;
        ServiceAdminUserEditData reqBody = null;
        ServiceDocsAdminUserGetSingle response = api.v1MgmtUserUserIDPut(userID, reqBody);
        // TODO: test validations
    }

}
